"""Pre-computes the Bayer-dithered gradient tiles used by the pink pop scheme and prints them as CSS custom properties.
   usage: python3 scripts/make-dither-tiles.py   (paste the output over the `DITHER TILES` block in assets/css/dos-skin.css)
   Each tile is a tiny PNG (8 px wide) that CSS scales up with image-rendering: pixelated, so every gradient is 1-bit-looking."""
import base64, io
from PIL import Image
def bayer(n):
    m = [[0]]
    while len(m) < n:
        s = len(m); o = [[0] * (s * 2) for _ in range(s * 2)]
        for y in range(s * 2):
            for x in range(s * 2):
                o[y][x] = m[y % s][x % s] * 4 + [[0, 2], [3, 1]][y // s][x // s]
        m = o
    return m
B = bayer(8)
def hexrgb(h): h = h.lstrip('#'); return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))
def tile(c1, c2, h, w=8):
    a, b = hexrgb(c1), hexrgb(c2); im = Image.new('RGB', (w, h))
    for y in range(h):
        t = y / max(1, h - 1)
        for x in range(w): im.putpixel((x, y), b if t > (B[y % 8][x % 8] + .5) / 64 else a)
    buf = io.BytesIO(); im.save(buf, 'PNG', optimize=True)
    return 'url("data:image/png;base64,%s")' % base64.b64encode(buf.getvalue()).decode()
TILES = {
  '--dz-page':  ('#c9a2ff', '#ff9bd6', 160),   # page background: lavender at the top fading to pink (x3 = 480px)
  '--dz-bar':   ('#ff5fc4', '#9b5cff', 8),     # title bars, taskbar, marquee
  '--dz-btn':   ('#ffe3f5', '#ff9bd6', 10),    # raised nav buttons
  '--dz-btn-on':('#ff6fd6', '#b57bff', 10),    # pressed / current nav button
  '--dz-card':  ('#ffd6ef', '#ffb4e2', 12),    # window bodies get a faint dithered wash
}
print('/* DITHER TILES (generated by scripts/make-dither-tiles.py) */\n:root[data-theme="pop"] {')
for k, (a, b, h) in TILES.items(): print('  %s: %s;' % (k, tile(a, b, h)))
print('}')
