"""Pre-computes the Bayer-dithered art for the LITERAL LEGEND scheme and prints it as CSS custom properties.
   usage: python3 scripts/make-dither-tiles.py   (output goes between the DITHER TILES markers in assets/css/dos-skin.css)
   Every gradient is a tiny 1-bit-looking PNG drawn with image-rendering: pixelated.
   Horizontal tiles (--dz-bar, --dz-rainbow) fade left to right; vertical tiles (--dz-page, --dz-btn*) fade top to bottom.
   Tiles display at 1x by default (--dz in the CSS scales them)."""
import base64, io, math, random
from PIL import Image
def bayer(n):
    m = [[0]]
    while len(m) < n:
        s = len(m); o = [[0] * (s * 2) for _ in range(s * 2)]
        for y in range(s * 2):
            for x in range(s * 2):
                o[y][x] = m[y % s][x % s] * 4 + [[0, 2], [3, 1]][y // s][x // s]
        m = o
    return m
B = bayer(8)
def th(x, y): return (B[y % 8][x % 8] + .5) / 64
def rgb(h): h = h.lstrip('#'); return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))
def uri(im):
    buf = io.BytesIO(); im.save(buf, 'PNG', optimize=True)
    return 'url("data:image/png;base64,%s")' % base64.b64encode(buf.getvalue()).decode()
def ramp(stops, w, h, axis):
    """stops: list of hex colours spread evenly along the axis; each pixel picks one of the two neighbouring stops by Bayer threshold."""
    cols = [rgb(c) for c in stops]; n = len(cols) - 1; im = Image.new('RGB', (w, h))
    for y in range(h):
        for x in range(w):
            t = (x / w if axis == 'x' else y / max(1, h - 1)) * n
            i = min(n - 1, int(t)); f = t - i
            im.putpixel((x, y), cols[i + 1] if f > th(x, y) else cols[i])
    return uri(im)
def clouds(W=256, H=192, seed=7):
    random.seed(seed); a = [[0.0] * W for _ in range(H)]   # coverage
    def puff(cx, cy, r):
        for oy in (-H, 0, H):
            for ox in (-W, 0, W):
                for y in range(max(0, int(cy + oy - r)), min(H, int(cy + oy + r) + 1)):
                    for x in range(max(0, int(cx + ox - r)), min(W, int(cx + ox + r) + 1)):
                        d = math.hypot(x - (cx + ox), (y - (cy + oy)) * 1.25)
                        if d <= r: a[y][x] = max(a[y][x], 1 - d / r * .2)
    def cloud(cx, cy, s):
        for dx, dy, r in [(-2.2, .6, 1.2), (-1.0, -.2, 1.7), (.4, -.6, 2.1), (1.8, -.1, 1.6), (2.8, .7, 1.1), (0, .9, 2.2)]:
            puff(cx + dx * s, cy + dy * s, r * s)
    cloud(60, 50, 9); cloud(190, 40, 6); cloud(150, 140, 11); cloud(30, 160, 5)
    im = Image.new('RGBA', (W, H), (0, 0, 0, 0))
    for y in range(H):
        for x in range(W):
            if a[y][x] > .5:
                below = a[min(H - 1, y + 4)][x] <= .5 or a[min(H - 1, y + 7)][x] <= .5       # underside of a puff gets a dithered pink shadow
                im.putpixel((x, y), (255, 214, 240, 255) if below and th(x, y) < .55 else (255, 255, 255, 255))
    return uri(im)
TILES = [
  ('--dz-bar',     ramp(['#ff2fa8', '#ff7ac8', '#ffb0dd'], 640, 8, 'x')),                         # title bars: hot pink to pale pink, left to right
  ('--dz-btn',     ramp(['#fff3fb', '#ffa6dc'], 8, 10, 'y')),                                    # raised candy buttons
  ('--dz-btn-on',  ramp(['#ff4fb8', '#ff9bd6'], 8, 10, 'y')),                                    # pressed / current
  ('--dz-rainbow', ramp(['#ff00ff', '#ff2020', '#ffff00', '#00ff00', '#00ffff', '#ff00ff'], 240, 8, 'x')),   # title text: the teletext colours
]
print('/* DITHER TILES (generated by scripts/make-dither-tiles.py) */\n:root[data-theme="legend"] {')
for k, v in TILES: print('  %s: %s;' % (k, v))
print('}\n/* END DITHER TILES */')
